# Kokkuvõte ja järeldused

\multicolsbegin

Teostasin oma erialase praktika gümnaasiumiastme füüsikaõpetajana Kohila Gümnaasiumis. \qty{156}{\hour} sisse mahutatud tegevuste tulemusena eksisteerivad praktikaperioodi kohta loodud õppesessioonide kavad, hulganisti arvutusülesannete tõlkeid ja lahendusi. Samuti olen teinud järeldused, kuidas edaspidi õpetamist nii teostada, et tervis ei kannataks.

Minu teoreetiline ettevalmistus füüsikaõpetamiseks oli piisav arvestades, et olin õpetajana tegutsenud üle kümne aasta ja osaliselt õpetatavat temaatikat õppinud ülikoolis. Siiski on mul olulisel määral puudu pedagoogikateadmistest ja -oskustest, mille tõttu ma ka võtsin ette ajamahuka teekonna integreeritud loodusteaduste bakalaureuseõppest vähemalt gümnaasiumi loodusteemade õpetaja magistratuuri lõpuni. Kuna ma polnud \num{25} aastat füüsika ja keemiaga süvitsi tegelenud, misjärel tekkis huvi nende valdkondade vastu, olin olulises osas põhikoolis ja gümnaasiumis õpitut unustanud. Abiks oli ülikooli esimene semester, milles esimesed füüsika ja keemia kursused olid kordavad. Kuna ülikoolis tuleb uut infot kiiremini peale, kui mina oma teadmiste ja oskuste varal suudan hallata, on mul nii mõnigi kursus lõpetamata.

Kohilas õpetatavate kursuste teemadest olid mulle alguses kõik jõukohased. Siiski tuli endale palju korralikumalt selgeks teha mõõtemääramatuse arvutamisprotsess. Kuigi ma ei mäletanud n-ö unepealt elektromagnetismi asju, oli nende meenutamine õpiku abil kiire. Pindpinevust olime jõudnud ülikoolis soojusõpetuse kursuses käsitleda, nii et 12. taseme kursuses alustasin sellest. Aine ehitus ning mikromaailm oleks minu jaoks olnud alguses liiga suur tükk, sest vastav temaatika oli ülikoolis käsitlemata. Seetõttu asusin hoopis rõhutemaatikat õpetama, mis on eelduseks pindpinevuse mõistmisele. Valikkursuse akustikateema oli mul täiel määral ülikoolis läbitud, mistõttu oli selle õpetamine nauditav. Takistusjõud oli siiski minu jaoks uus teema ja seda õppisin koos õpilastega muidugi eelnevalt ette valmistades. Edasiseks tõhusaks õpetamiseks on vajalik eeldus, et endal on õpetatav teema selge ja kursus on ette valmistatud.

Eri meetoditega püüdsin jõuda iga õpilaseni. Ometi oli kõigi õpilaste aktiveerimine ületamatu ja sooritamatu ülesanne. Kuigi seda mõjutavad minust mittesõltuvad tegurid nagu õpilaste ettevalmistus ja suhtumine, võiksid kasulikud pedagoogikanipid olla edasises õpetamises oluliseks abiks.

Praktika kestel sain ise õpetatavad teemad sellisel määral selgeks, et korra üle lugedes võiksin uuesti ja tõhusamalt õpetada. Kuna üks õpilane on düslektik, siis sain teada, mida see tema puhul tähendab. Sain nautida mentori tuge ja tunda, kui häiriv selle järgimine on kooli juhtkonnale. Vahetult enne õpetamist ja selle kestel läbi viidud kujundava hindamise koolituse raames sain meeldetuletust, kuidas tagasisidestada õpilasesõbralikult. Õppisin, et n-ö fassaad, mida näeme, kui asume kooli õpetama, võib olla tohutult ilus ja praktiline võrreldes tegeliku olukorraga. Selgus, et hinnata tuleb võimalikult tihti. Kogesin, et võimalik on õppekavast läbida vaid viiendik, kui õpilastel puuduv varasemast vastav ettevalmistus.

\multicolsend
