# Tööülesannete sooritamine

\multicolsbegin

## Tööülesanded

Asusin tööle koormusega \num{0,667}.

Minu tööülesanne oli õpetada füüsikat kahele kümnenda, kahele 11. ja kahele 12. taseme õpilaste rühmale.

Kursused, mida asusin läbi viima, olid füüsika põhiprogrammist *Füüsika meetod*, *Elektromagnetism* ning *Mikro- ja megamaailm*, ning 12. taseme lisakursus *Füüsika ja tehnika*.

Kõiki kursuseid said õpilased kaks korda nädalas korraga ühe sessiooni esmaspäeviti ja reedeti, välja arvatud 12. taseme kursused, millest põhikursus oli esmaspäeviti ja valikkursus reedeti.

Kuna mulle polnud ette antud mitte ühtki õppesessiooni läbiviimise kava, hakkasin kõiki nimetatud kursuseid looma nullist.

Õpetajaid kohustati esimese kontaktsessiooni kirjeldusse tekitama hindamisjuhendi[@kalmer_1], mis on minu konspekti osa. Lähtusin hindamisjuhendi koostamises kooli hindamise korraldusest[@Koostamise2001-jl].

Kohustuslik oli ka osaleda kooli poolt organiseeritud koolitustes, mis olid Kiusamisvaba Kooli ja kujundava hindamise teemades.

Erialasektsiooni siseselt osalesin koosolekutes ja ülekooliliselt õppenõukogu koosolekutes.

## Metoodika

Kuna tegemist oli minu esimese füüsikaõpetamisega ja ma pole vastavat pedagoogikat veel õppinud, lähtusin oma varasemast õpetajakogemusest kursuste loomises. Aeg töölepingu esimesest kuupäevast esimese õppesessioonini oli liiga napp selleks, et kõik kursused tervikuna eelnevalt läbi mõelda. Ka polnud ma jõudnud ülikoolis veel kõiki käsitletavaid teemasid õppidagi. Teadsin, et mul on kasutada kasulikud õppeallikad, mille baasil saan kõik kursused läbi viia. Need allikad on abiks, kuni ma oma kursuseid veel piisavalt valmis pole saanud, ja edaspidi täienduseks.

Leian, et tõhus on iga teema puhul käsitleda juppi teooriat, lahendada selle kohta hulganisti arvutusülesandeid ning kontrollida teooriat eksperimentaalselt, enne kui võtta ette järgmine jupp. Samuti peavad jupid olema üksteisega loogiliselt seotud. Iga järgmine jupp võib eeldada eelneva jupi valdamist.

Iseseisvaks lahendamiseks jäetavad arvutusülesanded lahendasin üldjuhul eelnevalt oma virtuaalsele tahvlile, et õpilastel oleks võimalik kontrollida ja võrrelda lahendusi[@looduseuurimine].

Igal õpilasel soovitasin kasutusele võtta A4-vormingus ruuduliste lehtedega kaustiku, kuhu õpilane lõi oma konspekti, st märkis üles kõik vajaliku ja kuhu lahendas ka ülesanded. Samuti oli õpilasel vaja eri värvi füüsilisi kirjutusvahendeid ja geomeetriavahendeid. Kalkulaator oli abiks keeruliste arvutuste puhul. Konspekti võis luua ka virtuaalselt, kui õpilasel on graafikatahvel. Sellisel juhul andsin kasutusse minu halduses oleva virtuaaltahvlite keskkonna, et kõik virtuaalsed konspektid oleksid ühes kohas[@wbo]. Viimast võimalust üks välisõpilane ka kasutas.

Kuna iga kontaktsessioon oli vaid \qty{45}{\minute} pikk, siis teadmiste-oskuste kinnistamiseks oli vajalik õpilasel lahendada hulganisti ülesandeid, lugeda, vaadata ja kuulata juurde väljaspool kontaktsessiooni.

Et hallata kõikide oma füüsikakursuste sisu, kalendrit, ülesandeid, teste, hindeid jms, lõin oma konspekti[@kalmer_sissejuhatus], mis on veebis avalikult kättesaadav ka trükiteisendina.

Kuna eksperiment on terviklik ja selle raport peab sisaldama kõike olulist, siis ei olnud mõtet eksperimentide protokolle eristavalt hinnata, vaid nõudsin kõige olulise olemasolu.

Plaanisin iga alamteema kohta teostada kontrolltöö ja kandsin need ka eKooli[@ekool] päevikutesse kohe alguses sisse.

Mulle on mu enda õppes sümpatiseerinud boonused. Üks boonussüsteem, mille kohaselt saab tegus õpilane oma selgitamistega õppeprotsessis olulise osa kursuse lõpphinnet kätte ja peab eksamis vähem pingutama, on Kert Martma üldkeemia ülesannete lahendamised. Seetõttu juurutasin sarnase süsteemi Kohilasse, kuigi oluliselt tagasihoidlikuma punktiarvestusega, et utsitada õpilasi aktiveeruma.

Et eristavas hindamises on Kohila Gümnaasiumis täisarvulised hinded ühest viieni, mõtlesin kontrolltööde jaoks välja viiest ülesandest koosneva süsteemi, millest esimeses pidi õpilane midagi selgitama, teises midagi tuletama ja ülejäänutes midagi arvutuslikult lahendama. Arvutusülesanded olid kolme raskusastmega. Kõige lihtsama ülesande puhul ei olnud vaja uut valemit kokku panna.

Pidasin oluliseks, et õpilane saaks minu hindamisest aru. Seetõttu pidi õpilane pärast minupoolset hindamist saama oma lehe(d) minu kommentaaridega tagasi, lahendama kõik ülesanded oma konspekti, kommenteerima oma sooritust ja panema ise endale hinde. Seejärel plaanisin sisestada hinde eKooli koos oma põhjaliku tagasisidega iga ülesande lõikes. Kontrolltööde arvutusülesannete näidislahendused plaanisin samuti õpilastele tekitada.

Kuna mulle on hakanud meeldima MathCityMapi[@mathcitymap] kasutamine, siis tahtsin koostada kontrolltöid ka sellega läbimängimiseks välistingimustes. Plaan oli ka valida välja universaalsed ülesanded ja nendest püsirada koostada, mille põhjal taotleda MathCityMapi koolipartnerlust.

Kuna mulle eristav hindamine ei meeldi, sest kui ma ikka olen alles Märjamaas, siis ma ei ole Pärnus ega saa meres supelda, kasutasin valikkursuse puhul võimalust mitteeristavaks hindamiseks.

Oma konspekti kirjutasin üles soovitused õppimiseks[@kalmer_2023_2].

Järgnev osa minu konspektis on *Baasreeglistik*, milles on loogilises järjekorras põhilised sisulised reeglid[@kalmer_3]. Mõned osad, mis muudes õpikutes ei ole piisavalt hästi või on vigaselt seletatud, pidasin vajalikuks korralikult kajastada enda konspektis.

Iga kursuse kohta oma konspektis kirjutasin esmalt õppekavast[@Ainevaldkonna_undated-bs] välja õpitulemused, õppesisu, põhimõisted ja praktilise tegevuse soovituse. Kuna õpetasin ka muus koolis, siis järgnevalt esitasin kummagi kooli kalenderplaani. Iga kontaktsessiooni kohta kirjutasin välja kava, seosed õppekavaga, mida kestvalt muutsin vastavalt tegelikule olukorrale. Tavaliselt valmistasin ühe koolipäeva kaupa ette, sest ajalist varu enamaks polnud.

Konspekti järgmine osa sisaldab ülesandeid iseseisvaks lahendamiseks, mis on kõik *Physics for Scientists Engineers by Douglas Giancoli, (z-lib.org).pdf*'i[@physics] lahenditega ülesanded, millest kõik, välja arvatud triviaalsed, lahendasin oma virtuaalsele tahvlile.

Kursuse viimane osa minu konspektis on kontrolltööde ülesannete ja testitulemuste päralt.

Eraldi peatükina kirjeldan oma konspektis mõõtmiseksperimendi läbiviimist, kuna eriti just mõõtemääramatuse teema on väga mahukas ja segane[@kalmer_2024_9].

## Tulemused

Osalesin Kiusamisvaba Kooli ja kujundava hindamise koolituses. Võtsin osa uute töötajate orientatsioonisündmusest ning kahest õppenõukogu koosolekust. Osalesin kahes loodusteaduste õpetajate koosolekus.

Praktikalepingu perioodis valmistasin ette ja viisin läbi 13 õppesessiooni eraldi kahele kümnenda taseme rühmale kokku 35 õpilasega, 14 õppesessiooni eraldi kahele 11. taseme rühmale kokku 39 õpilasega, seitse õppesessiooni põhifüüsikas eraldi kahele 12. taseme rühmale kokku 51 õpilasega ning seitse õppesessiooni *Füüsikat ja tehnikat* eraldi kahele 12. taseme rühmale. Tegevused jätkusid pärast praktikaperioodi lõppu.

Valmistasin mõõtmise õppimise struktuuri ja kompaktse mõõtemääramatuse arvutamise eeskirja.

Koostasin konstantide ja ühikute tuletamise skeemi.

Koostasin kinemaatika ja elektromagnetismi käsitletud osade valemite tuletamise ja sõltuvuse skeemi.

Füüsika meetodi osas käsitletud alamteemad:

1. teaduse olemus,

2. tulevikusoovid ja seosed füüsikaga,

3. mudelid, teooriad ja seadused,

4. teaduste piirid,

5. kümne astmed,

6. põhjuslik seos,

7. füüsika üldprintsiibid,

8. ühik,

9. mõõtühikute eesliited,

10. ümardamine,

11. tüvenumbrid,

12. ühikute teisendamine,

13. Le Système international d'unités,

14. dimensionaalanalüüs,

15. tabavus, täpsus, veatüübid ja määramatus (alustasime).

Valmistasin *Plickers*i[@a2020_plickers] testid järgnevate teemade kohta ning kasutasin kaardistamiseks enne ja pärast teemakäsitlust:

1. teaduse olemus,

2. mudelid, teooriad ja seadused.

*Plickers*iga soovisin näha, et pärast teemakäsitlust on samade küsimuste puhul tulemused paremad, kuid see mitte alati nii ei olnud, vaid oli ka kehvemaid tulemusi.

Elektromagnetismi kursuses käsitlesime järgmised alamteemad:

1. staatiline elekter, elektrilaeng ja selle jäävus,

2. elektrilaeng aatomis,

3. isolaatorid ja elektrijuhid,

4. indutseeritud laeng ja elektroskoop,

5. Coulomb' seadus,

6. elektriline aku,

7. elektrivool,

8. induktsioon, konduktsioon, maandamine.

Valmistasin *Plickers*i testid järgnevate teemade kohta ning kasutasin kaardistamiseks enne ja pärast teemakäsitlust:

1. staatiline elekter, elektrilaeng ja selle jäävus,

2. elektrilaeng aatomis,

3. isolaatorid ja elektrijuhid,

4. indutseeritud laeng ja elektroskoop.

Ainsa eksperimendi, mille õppesessioonis läbi viisime, käigus valmistasid õpilased elektroskoope, mille liigitasin kolme kategooriasse, need, mis

1. hästi töötasid,

2. kesiselt töötasid, ja

3. ei töötanud.

Protokolli suutsid kas kohe või minu tagasiside põhjal korrektselt vormistada ja esitada seitse õpilast.

Esimene kontrolltöö elektromagnetismi kursuses oli sisetingimustes ja selle suutsid kas otse või järelvastamise kaudu vähemalt hindele *3* teha 23 õpilast.

Mikro- ja megamaailma kursuses käsitlesime järgmised alamteemad:

1. aine faasid,

2. tihedus ja eritihedus,

3. pindpinevus ja kapillaarsus,

3. rõhk voolises,

4. atmosfääriline ja manomeetriline rõhk,

5. Pascali põhimõte,

6. rõhu mõõtmine, mõõdikud ja baromeeter.

Füüsika ja tehnika kursuses käsitlesime kahe mooduli teemasid:

1. aero- ja hüdrodünaamika: keskkonna takistusjõud,
 
2. elastsuslained:

 - pikilained,
 
 - heliintensiivsus, detsibellid,
 
 - heli allikad.

Tõlgitud ja läbilahendatud ülesannete arv vastavalt kursusele praktikaperioodis:

- füüsika meetod: 28,

- elektromagnetism: 53,

- mikro- ja megamaailm: 15,

- füüsika ja tehnika: 31.

Füüsika meetodi testi järgselt muus koolis valmistasin esitluse Kohila Gümnaasiumi õpilastele teiste õpilaste vigadest õppimiseks[@quartoinput07e590ee].

## Arutelu

Eriala praktikaga seostan järgmised Tallinna Ülikoolis läbitud või läbimises olevad kursused:

1. digipädevus ja akadeemilised väljendusoskused,

2. õppimine ja õpetamine keemias,

3. soojusõpetus,

4. akustika muusikas: inimhäältest pillideni,

5. füüsikaline maailmapilt ning

6. üldmõõtmised loodusteadustes.

Digipädevuse ja akadeemiliste väljendusoskuste kursuses õppisin kasutama välisviiteid, nende haldamise keskkondi ja ehitama üles väljundit vastavalt eeskirjale. Omandatud teadmisi-oskusi kandsin õpilastele edasi eksperimentide protokollide vormistamise kaudu.

Mul oli plaan teha õpilastega mitu eksperimenti. Siiski juba esimene eksperiment - elektroskoobi valmistamine - osutus raporteerimise mõttes enamikule üle jõu käivaks. Kui vormistuse suhtes ma rangeid piiranguid ei seadnud, siis sisu osas ei tohtinud protokoll jama sisaldada. Püüti liiga lihtsalt läbi saada jättes selgitamata teooriaosa, millest paistnuks välja, kas õpilane sai aru, mida üldse tegi. Kui siis teooriaosa täiendati, selgus vahel, et ei oldudki aru saadud. Seetõttu korraldasin ühe ekstra sessiooni selgitamaks üksnes elektroskoopiat tekitades tahvlile kompaktselt enne- ja pärast-skeemid induktsiooni, konduktsiooni ja maandamise kohta oodates õpilastelt nende skeemide märkimist oma konspekti ja hiljem protokolli. Vähesed lisasid neid skeeme. Kuna mina neile polnud eksperimendi protokolli vormistamist õpetanud, siis tuli mul ka seda teha.

Üks õpilaste klassijuhataja soovitas mul *latt alla lasta*. Vastasin, et ma pigem teen lõpus eraldi sessiooni, milles on võimalus igal õpilasel oma protokoll korda saada. Kuna eksperimendi protokollimine on teaduse tähtis osa ja füüsika on fundamentaalne loodusteadus, siis tähendaks *lati allalaskmine* rumalamaid õpilasi, kes arvavad, et rohkemat neilt oodata ei tohigi.

Õppimine ja õpetamine keemias oli abiks seeläbi, et me olime ülikoolis korra reaalselt üht keemiateemat gümnasiastidele õpetanud. Kuna toona kasutasin Plickersit, siis tegin seda ka nüüd. Kümnenda taseme esimene füüsika kursus on *Sissejuhatus. Kulgliikumise kinemaatika*. Selle sissejuhatav osa koosneb füüsika määratlusest ja füüsika meetodist. Kuna füüsika määratluse puhul pole midagi praktilist teha, vaid ainult arutleda, siis otsustasin luua valikvastustega küsimused õpilastele ning neidsamu küsimusi kasutada vahetult enne ja vahetult pärast teema käsitlemist. Kasutasime selleks *Plickers*i kaarte. Tulemused toona ja nüüd olid sarnased. Osa õpilasi vastas pärast paremini, osa õpilasi kehvemini. Sarnase tulemuseni jõudsime elektromagnetismi üldsõnalises osas. Põhjusi unustamiseks võib olla mitmeid, millest esitan siinkohal kaks:

1. Õpilased märkisid vastuseid sõltumata sellest, mida nad teadsid või arvasid.

2. Tähelepanu oli hajutatud õpilase enda kõrvalise tegevuse poolt õppimise või kontrollimise kestel.

Soojusõpetuse kursus seostus kõige rohkem mikro- ja megamaailma kursuse pindpinevuse teemaga.

Kõige enam rakendasin enda õpitut akustika kursuse puhul. Kuna füüsika ja tehnika kursus koosneb valikmoodulitest, siis lasin õpilastel esimeses sessioonis valida neid huvitavad teemad. Kuna neli moodulit olid kahe rühma õpilastel samad, siis kahega nendest moodulitest ka alustasime.

Esimesena võtsime ette aero- ja hüdrodünaamika ning selles keskkonna takistusjõu. Plaan oli läbi viia eksperiment, mille olin varem ülikoolis läbi viinud, ja hakkasin selle jaoks vahendeid kokku otsima. Sööklas tööõpetuse õpetajaga arutelu päädis tema poolt mulle üleantud tikutopsiga, milles on laagritest pärit kuulid. See temaatika on *Physics for Scientists Engineers by Douglas Giancoli, (z-lib.org).pdf*'s[@physics] laiali. Esmalt võtsime ette kiirusest sõltuvad jõud: takistus- ja lõpliku kiiruse. Oli huvitav selgitada, et langevate esimete kiirus suureneb kuni lõpliku kiiruseni, samuti vastavat valemit tuletada kasutades 12. klassitasemel värskelt õpitud integreerimist. See tekitas tegusaimate õpilaste seas kohese vastumeelsuse, kuna nad pidid pingutama, et aru saada. Siiski sai neile kõik arusaadavaks, sest nad esitasid järjepanu küsimusi, kuidas ühest asjast teine saadi.

Kuna ülejäänud mooduli teemad tundusid olevat seotud vooliste peatükiga ja vooliste peatükk oli mul põhikursuse peatükk, siis otsustasin jätkata esimese mooduliga pärast selle peatüki esimeste osade käsitlemist põhikursuses.

Järgmisena võtsimegi ette elastsuslained ja ilma selgitamata, mis on elastsuslaine, sukeldusime akustikasse, mille kohta on *Physics for Scientists Engineers by Douglas Giancoli, (z-lib.org).pdf*'s[@physics] eraldi peatükk *Heli*. Tassisin kaasa plokkflöödi. Kohapeal oli kitarr. Õpikus on praktilised arvutusülesanded ja valemite tuletuskäigud, mille tegin tahvlile läbi. Neid sai siis ilmestada pillidega. Ükskord ei jäänud üks edumeelne õpilane rahule, et ei suutnud õppesessioonis lahendini jõuda. Nii jäime üheskoos arutlema veel järgmiseks sessiooniks, kuni lahend oli välja arvutatud.

Kui füüsikalise maailma pildi õpetaja Ako Sauga mind õpetas, meeldis mulle tema süstemaatilisus. Tal oli igaks õppesessiooniks uus teema koos mitmevärviliste slaididega ja igas nädalas saime testida oma teadmisi-oskusi Moodle's olevate ülesannetega. Tahtsin oma õpilastele pakkuda sarnast süsteemsust, aga aeg seadis oma piirid.

Kui ma ülikoolis üldmõõtmisi loodusteadustes õppisin, tegin kõik kaasa ja küsisin detailide kohta, mille kohta vahel õpetaja Tõnu Laas jagas selgitusi, vahel mitte. Nii jäigi mõni osa segaseks. Kuna kursuse hinne oli mitteeristav, siis piisas ka ainult poole kursuse läbimisest ja nii ma ka tegin. Tõnu konspekt tundus mulle vigane ja igav. Nüüd, kui õpetasin ise mõõtemääramatust, ei jäänud mul muud üle kui teema endale korralikult selgeks teha. Kasutasin selleks nii inglis- kui prantsuskeelseid allikaid. Ühes oli selgitatud ühtmoodi, teises teistmoodi. Lõpuks tundus kunagine vihatud Tõnu konspekt kõige selgemana. Valmistasin oma esialgse mõõtemääramatuse arvutamise juhendi osaliselt selle järgi. Tahtsin teha näited eri mõõtevahendite kohta.

Kuna ma polnud ülikoolis kõiki gümnaasiumifüüsika kursuseid läbinud, sai mu õpetamine toimuda kahasse iseõppimisega. Kuna töölepingu algushetkest esimese õppesessioonini oli veidi üle nädala, siis polnud võimalik kõiki läbiviidavaid kursuseid täiel määral plaanida ega ette valmistada. Seetõttu valmistasin koolipäevade plaane ette ühekaupa. Kui koolipäev oli läbi, asusin ette valmistama järgmist koolipäeva.

Õppesessiooni ettevalmistamine toimus niimoodi, et vaatasin esmalt eKoolist järele, kuhu olime viimati jõudnud, lugesin *Physics for Scientists Engineers by Douglas Giancoli, (z-lib.org).pdf*'st[@physics] juurde ja märkisin kava enda konspekti koos viidetega. Kui vastav osa oli läbitud, siis tõlkisin ja lahendasin ka ülesanded ning andsin õpilastele lahendada. Ühe \num{45}-\unit{\minute} sessiooni ettevalmistamine kestis mul tavaliselt kauem kui sessioon ise. Pidasin oluliseks endale teema hästi selgeks saada. Kuigi enamus õpilasi olid jäänud oma arengus põhikoolitasemele, siis võinuksin küll ka lihtsamate selgitustega piirduda, ent kasulikum oli kohe anda õpilastele õige selgitus. Kord üks õpilane küsis, miks on dielektriline konstant dielektriline, ja ma arvasin, et *di-* on nagu läbiv ja seetõttu. Alles hiljem oskasin talle seletada, et see tähendab elektrilist läbitavust mitteelektrikutes. Ma polnud sellele ülikoolis õppides mõelnud. See on vaid üks näide, kuidas õpetamise kaudu ma õppisin kõige rohkem.

Ainsa kontrolltöö, mille jõudsin praktikaperioodis läbi viia, ettevalmise tegin ka põhjaliku koostades õpilastele võimalikult palju erinevaid ülesandeid, et vältida üksteise pealt mahakirjutamist. See tähendas hiljem olulist ajakulu hindamises ja tagasisidestamises. Õpilaste jaoks, kes läksid järelvastamisse paremat hinnet nõutama, koostasin omakorda uued ülesanded ning mõistagi tuli need läbi lahendada ja hiljem õpilase sooritus hinnata.

Harv polnud olukord, mil sain vahetult enne koolipäeva algust magada üksnes tunni. Kuna koolis olid mul kuus sessiooni järjest, siis oli see aeg tegevusi täis ja nii ma koolis õpetades väga väsimust ei tundnud, kuigi olin uimas. Alles pärast koolipäeva lõppu autos olles kasutasin võimalust juhtimaks liiklusvahendi jõe juurde, et saada ülekehalist värskendust jahedas jõevees enne pooletunnist tagasisõitu, mis vahel sisaldas endas tunnist tukkumispausi parklas, sest ma ei jõudnud autost väljuda. Kuna ma sellises rütmis jätkasin ka pärast praktikaperioodi, jõudsin aasta viimaseks päevaks läbipõlemisse ehk keha haigestus kolmandat korda uude moodsasse haigusse, mille sümptomitest taastun siiamaani, kui seda aruannet kirjutan.

Soovisin alguses kasutada võimalikult palju praktilisi vahendeid, kuna Kohila Gümnaasiumis neid jätkus. Paraku kulus õpilaste turgutamisele arvutusülesannetega liigselt aega. Minu kui õpetaja ootus oli, et vastava taseme õpilastel on vastav teadmiste-oskuste tase. Kui selgus, et lausa 12. taseme õpilastel oli vajaka seitsmenda taseme matemaatika oskusi, siis ei saanud me ometi seda probleemi jätta tähele panemata ja tuli vastavad lüngad täita.

Teisest küljest õpetasin õpilastele matemaatikavõtteid, millega nad alles oluliselt hiljem matemaatikakursuses kokku puutuvad. Nt on vaja õppekava järgi mõista 11. tasemel $E$-vektorit ja superpositsiooni. Nii ma neile õpetasin vektorite liitmist ja vektorarvutust tuletades meelde trigonomeetriat. Kinemaatikat on nii palju lihtsam mõista, kui mõistetakse tuletist. Ja isegi veel varem tuli minul tuletis mängu: nimelt mitme sisendiga mõõtemääramatuse arvutamises. Nii et seda õpetasin ma ka. Tuletise puhul selgitasin olemust, näitasin põhivalemi, tuletasin mõned otseteed, ülejäänud andsin ette.

Õpetamise kestel tundsin hästi suurt puudust erialasest lõimimisest. Juba mainisin, milliseid matemaatika tööriistu füüsika jaoks liiga hilja käsitletakse. Ometi ei ole neil riistu võimalik matemaatikakursuses ka varem käsitleda, kuna vahepeal on veel hulganisti vahendeid, mis vaja selgeks saada, mis aitavad nende tööriistade kasutamist mõista. Seega oleks mõistlik viia läbi kõik gümnaasiumi matemaatikakursused esimese aastaga jättes viimased kaks aastat rakendusteadusteks.

Seoses lõimimisega tajusin, kuidas õpilased ei oska seostada võõrkeele kasutamist konkreetse õpivaldkonnaga. Õpilane, kes kiitles oma inglise keele oskusega, keeldus õppimast ühe käe näppudel loendatavat arvu erialaseid termineid, et lahendada ingliskeelsed arvutusülesanded.

Puudu on Kohila Gümnaasiumis ühistest aruteludest nende vahel, kellel on probleem, ja nende vahel, kes saavad aidata. Praeguse süsteemi järgi tähendab abi seda, et kui tagurlik õpilane otsib võimalusi mitteõppimiseks, siis talle neid ka võimaldatakse ja karistada saab õpetaja. Seda aetakse hoolekogu, direktori ja õppejuhi kaudu.

Jäin väga rahule oma mentoriga, kes on lisaks muljetavaldavale praktilisele pädevusele füüsikaõpetamise valdkonnas meeldiv inimene. Tema kirjeldas mulle olukordi, mis olid tal varem ette tulnud, ja andis nõu. Mentori soovituste järgi talitasin.

Sain Kohila Gümnaasiumis oma esimese füüsikaõpetamise kogemuse ja neid kogemusi soovin ohtralt juurde hankida, kuigi mitte enam nii tervist kahjustaval moel ja loodetavasti keskkonnas, milles õpetajat väärtustatakse ja õpilaste tegelik tase kirjutatule vastab.

Õpetaja, kes õpetamise kestel alles loob õpetatavat kursust, veerandkoormus peaks tähendama täiskoormust.

Kirjutan järgnevalt, kuidas ma õpetatud kursuseid edaspidi õpetaksin.

Füüsika meetodi kursuse arutelu teemade puhul ei muudaks ma esialgu midagi. Mõõtmise järjekorra osas lähtuksin omavalmistatud skeemist[@kalmer_3]. Koostaksin ise eestikeelsed reeglid ja  variatsiooniülesanded. SI puhul tutvustaksin ikkagi ametlikku brošüüri, sest selle ametlikud keeled on prantsuse ja inglise keel. Teeksin eraldi harjutuse terminite kohta võõrkeeltes. Õppekavas ei ole dimensionaalanalüüsi, mis on siiski abiks valemite kontrollimises. Dimensioonid on SI osa ja seetõttu õpetaksin selle analüüsi ikkagi. Mõõtemääramatuse arvutamise kohta olen praeguse raporti kirjutamise ajaks kirjutanud tervikjuhendi ja järgiksin seda. Viiksin läbi vähemalt kahe sessiooni jagu mõõtmiseksperimente, et õpilased saaksid kõik eri olukorrad kaetud. Leian, et mõõtmise osa on baas, mis peab olema selge, et edaspidi lahendada korrektselt arvutusülesandeid ja koostada eksperimentide protokolle. Selleks võiks isegi õppekavas kirjeldatud praktilise osa katta.

Elektromagnetismi õpetamises lähtuksin valemite komplekssusest, nii et alustaksin võimalikult lihtsa valemiga ja liiguksin edasi sammhaaval kompleksemate valemitega kasutades enda skeeme[@fsikakonstandid; @elektromagnetism].

Mikro- ja megamaailma õpetamises alustasin ma *Physics for Scientists Engineers by Douglas Giancoli, (z-lib.org).pdf*'i[@physics] järjekorrast ja selles oli kõige varasem õppekava teema pindpinevus, mille paremaks selgitamiseks otsustasin üle käia ka kõik eelnevad osad samas peatükis, mis, nagu selgus, on põhikooli teemad, kuigi õpilased ei olnud neid voolisteasju õppinud, vaid põhikoolis oli neil põhirõhk olnud asetatud elektrile. Edaspidi ma ei kulutaks aega eeldusteemadele isegi, kui need on läbimata, sest muidu ei jõuaks põhiteemasid korralikult käsitleda.

Füüsika ja tehnika kursuses ei ootaks ma põhikursuse teemade käsitlemise lõppu, vaid asuksin kohe mooduli teemade kallale. Elastsuslainete mooduli põhjal jõuaks kuue nädalaga läbida viiendiku mooduli teemasid.

Kuna ma ei teadnud, kui kaua mingi teema käsitlemiseks aega kulub, siis toimetasin rahulikult vastavalt *Physics for Scientists Engineers by Douglas Giancoli, (z-lib.org).pdf*'ile[@physics]. Oli valida, kas käsitleda kiirkorras kõiki õppekavas olevaid alamteemasid, mille tulemusel ei mäletaks õpilased aasta pärast, mida ja miks nad õppisid, või käsitleda põhjalikult mingeid baasalamteemasid, mille tulemusel mäletaksid ja oskaksid kasutada õpilased umbes kümnendikku õpitust. Kuna õppejuht ütles mulle, et õppekava on õpetaja jaoks A ja O, siis edaspidi peaks ehk kasutama seda kiirkäsitluse varianti. Samas, kui A on algus ja O on umbes keskel, siis võiks ka käsitleda baastemaatikat ja midagi keskelt. Eelistan siiski, et minu tööst kasu oleks ja sellest on kasu, kui õpilased vähemalt mingit osa minu õpetatust kasutavad.

Abiks on õpetamises kindlasti eelnev ettevalmistus. Ma õppisin õpetatavat koos õpilastega tehes teema eelnevalt endale selgeks. Ülikoolis on mul veel läbimata teemasid. Kui oleks piisavalt aega valmistada ette terve kursus, siis oleks õpetamine palju tõhusam ja tervis tugevam.

Sättisin iga kursuse alguses paika ka hindamisreeglid. Plaanisin teha vastavalt *Physics for Scientists Engineers by Douglas Giancoli, (z-lib.org).pdf*'i[@physics] struktuurile iga peatüki kohta ühe kontrolltöö. Tegelikkuses kestis teemade käsitlemine oluliselt kauem ja nii kujuneski, et praktikaperioodis ei jõudnud ma kümnenda ja 12. taseme õpilasi üldse hinnata. Edaspidisteks kursusteks mõtlesin süsteemi ja juba ka kasutan seda muus koolis, milles teen lühikontrolli iga õppesessiooni alguses alates teisest eelneva õppesessiooni sisu kohta. See on hindeline kontroll. Kursuse lõpus on kontrolltöö, milles on õpilasel võimalik neid tüüpi ülesandeid lahendada, mille hindega ta rahul pole. Niiviisi võiks järg olla paremini käes ja õpilastel on võimalik saada hinne lühikese perioodi õppimise kohta.

11\. taseme õpilasi õpetades tehti õpilaste poolt kaks ettepanekut, mille järgi hakkasin toimetama. Paar ülesannet olid sellised, mille näidislahendust kirjutasin terve tahvli täis ja mille sooritust ei jõudnud ühe õppesessiooniga lõpetada. Need olid sellised vektorülesanded, milles tuletasin tervikvalemi. Isegi sellisele tervikvalemile dimensionaalanalüüsi tegemine oli ajamahukas. Seetõttu tegi õpilane ettepaneku, et nii mahukate tervikvalemite asemel teeksime arvutused jupikaupa. Teine ettepanek oli kasutada õpperuumis olevat eestikeelset ülesannete kogumikku.

Oluliseks abiks oleks õpetamises, kui ma jõuaksin eelnevalt kogu kursuse sisu luua, kirjutada selleks miniõpiku, luua vaiksele õpetamisele ja variatsiooniteooriale põhineva iseõppimise tarkvara. Samuti võivad olla abiks eelmiste õpetajate õppesessioonide täiskavad, kuigi need pruugivad minu metoodikast erineda.

\multicolsend
